In [1]:
# DOCSTRING

# -- PREMIERE OBSERVATION : Il y a trois types de donnees en tout, par ordre de croissance, nous avons Objet suivie de Float64 et Int64
# -- DEUXIEME OBSERVATION : Il y a aucun doublons, que se soit sur les lignes entieres ou uniquement sur les IDs et Enormement de valeurs manquantes, au total : 60071 
# -- TROISIEME OBSERVATION : A propos de la variable cible "Credit_Score", il y a beaucoup plus de client avec un Credit_Score Standard (<=50000), ensuite vient Poor(~30000) et il y a tres peu de Good (se rapproche de 20000 clients)

In [1]:
## EXPLORATION DES DONNEES

In [2]:
# IMPORTATION DES DIFFERENTES LIBRAIRIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
# CHARGEMENT DES DU FICHIER .CSV
df = pd.read_csv(r"E:\Localhost_Academy (IA et Data Analysis)\eval_mi_parcours\data\train.csv", low_memory=False)

In [14]:
# EXPLORATION GLOBLALE DU PROJET

In [15]:
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [17]:
# Nombre de ligne x colonne
print(f"Dimensions : {df.shape[0]} lignes × {df.shape[1]} colonnes")

Dimensions : 100000 lignes × 28 colonnes

In [19]:
# Afficher les types
print("===============Les differents types des colonnes=======================")
df.dtypes

===============Les differents types des colonnes=======================

ID                           object
Customer_ID                  object
Month                        object
Name                         object
Age                          object
SSN                          object
Occupation                   object
Annual_Income                object
Monthly_Inhand_Salary       float64
Num_Bank_Accounts             int64
Num_Credit_Card               int64
Interest_Rate                 int64
Num_of_Loan                  object
Type_of_Loan                 object
Delay_from_due_date           int64
Num_of_Delayed_Payment       object
Changed_Credit_Limit         object
Num_Credit_Inquiries        float64
Credit_Mix                   object
Outstanding_Debt             object
Credit_Utilization_Ratio    float64
Credit_History_Age           object
Payment_of_Min_Amount        object
Total_EMI_per_month         float64
Amount_invested_monthly      object
Payment_Behaviour            object
Monthly_Balance              object
Credit_Score                 object
dtype: object

In [23]:
# STATISTIQUE DESCRIPTIVE
df.describe()

,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Delay_from_due_date,Num_Credit_Inquiries,Credit_Utilization_Ratio,Total_EMI_per_month
count,84998.000000,100000.000000,100000.00000,100000.000000,100000.000000,98035.000000,100000.000000,100000.000000
mean,4194.170850,17.091280,22.47443,72.466040,21.068780,27.754251,32.285173,1403.118217
std,3183.686167,117.404834,129.05741,466.422621,14.860104,193.177339,5.116875,8306.041270
min,303.645417,-1.000000,0.00000,1.000000,-5.000000,0.000000,20.000000,0.000000
25%,1625.568229,3.000000,4.00000,8.000000,10.000000,3.000000,28.052567,30.306660
50%,3093.745000,6.000000,5.00000,13.000000,18.000000,6.000000,32.305784,69.249473
75%,5957.448333,7.000000,7.00000,20.000000,28.000000,9.000000,36.496663,161.224249
max,15204.633333,1798.000000,1499.00000,5797.000000,67.000000,2597.000000,50.000000,82331.000000

In [29]:
# VALEURS MANQUANTES
print("=== Valeurs manquantes par colonne ===")
missing = df.isnull().sum()
print(missing.sort_values(ascending=False))
print(f"\nTotal valeurs manquantes : {missing.sum()}")

=== Valeurs manquantes par colonne ===
Monthly_Inhand_Salary       15002
Type_of_Loan                11408
Name                         9985
Credit_History_Age           9030
Num_of_Delayed_Payment       7002
Amount_invested_monthly      4479
Num_Credit_Inquiries         1965
Monthly_Balance              1200
ID                              0
Changed_Credit_Limit            0
Payment_Behaviour               0
Total_EMI_per_month             0
Payment_of_Min_Amount           0
Credit_Utilization_Ratio        0
Outstanding_Debt                0
Credit_Mix                      0
Delay_from_due_date             0
Customer_ID                     0
Num_of_Loan                     0
Interest_Rate                   0
Num_Credit_Card                 0
Num_Bank_Accounts               0
Annual_Income                   0
Occupation                      0
SSN                             0
Age                             0
Month                           0
Credit_Score                    0
dtype: int64

Total valeurs manquantes : 60071

In [34]:
# COMPTAGE DES DOUBLONS
print(f"=== Doublons ===")
print(f"Nombre de lignes dupliquées : {df.duplicated().sum()}")

# NOMBRE DE DOUBLONS AVEC LE MEME ID
print("=============NOMBRE DE DOUBLONS SUR LA COLONNE ID=================")
doublon = df.duplicated(subset=["ID"])

=== Doublons ===
Nombre de lignes dupliquées : 0
=============NOMBRE DE DOUBLONS SUR LA COLONNE ID=================

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [35]:
# ANALYSE DE LA VARIABLE Credit_Score

In [36]:
df["Credit_Score"].value_counts()

Credit_Score
Standard    53174
Poor        28998
Good        17828
Name: count, dtype: int64

In [1]:
# LE GRAPHE DE REPARTITION
sns.countplot(data=df, x="Credit_Score")

NameError: name 'sns' is not defined